[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
aarch64-paging = { version = "0.10.0" }
buddy_system_allocator = "0.11.0"
dtb = "0.2.0"
flanterm = "0.0.2"
limine = "0.5"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
